import type { Metadata } from "next";
import "./globals.css";
// import Navbar from "@/components/navbar";
import Image from "next/image";
import GoogleMapsProvider from '@/components/providers/GoogleMapsProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* <Navbar /> */}
        <div className="absolute inset-0 z-0">
          <Image
            src="/carbon-fiber.png"
            alt="Carbon Fiber Background"
            fill
            className="object-cover opacity-70"
          />
        </div>
        <GoogleMapsProvider>
        {children}
        </GoogleMapsProvider>
      </body>
    </html>
  );
}
